baseURL = 'https://mehmetsat.github.io/'
languageCode = 'en-us'
title = 'Mehmet Sat | Personal Blog'
theme = 'paper'
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
[mediaTypes]
[mediaTypes."text/markdown"]
  suffixes = ["md", "markdown", "mmark"]
[params]
  math = true 